name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - develop
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

  install:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Build project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to environment
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Deploying to production...";
          elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "Deploying to staging...";
          else
            echo "Deploying to development...";
          fi

